require("core.bootstrap")
require("themes.neovide")
require("core.basic")
require("core.keymaps")
require("core.autocmds")
require("themes.init")
require("lazy").setup(require("plugins"))
require("lang.init")
require("lang.completion")
pcall(require, "lang.rust")
require("ui.terminal.init")
require("debug.init")
