require "plugins.lualine"
require "plugins.bufferline"
require "plugins.nvim-treesitter"
require "plugins.comment"
require "plugins.which-key"
require "plugins.nvim-autopairs"
require "plugins.gitsigns"
require "plugins.colorizer"
require "plugins.conform"
require "plugins.nerd-icons"
require "plugins.theme"
require "plugins.trouble"
require "plugins.snacks"
require "plugins.xcodebuild"
require "plugins.lsp-progress"
require "plugins.noice"

